vim.cmd("let g:airline_theme = 'nord'")
vim.cmd('let g:airline_powerline_fonts = 1')
vim.cmd("let g:airline_symbols = {}")
-- powerline symbols
vim.cmd("let g:airline_left_sep = '»'")
vim.cmd("let g:airline_left_sep = '▶'")
vim.cmd("let g:airline_right_sep = '«'")
vim.cmd("let g:airline_right_sep = '◀'")
vim.cmd("let g:airline_symbols.linenr = '␊'")
vim.cmd("let g:airline_symbols.linenr = '␤'")
vim.cmd("let g:airline_symbols.linenr = '¶'")
vim.cmd("let g:airline_symbols.branch = '⎇'")
vim.cmd("let g:airline_symbols.paste = 'ρ'")
vim.cmd("let g:airline_symbols.paste = 'Þ'")
vim.cmd("let g:airline_symbols.paste = '∥'")
vim.cmd("let g:airline_symbols.whitespace = 'Ξ'")

-- airline symbols
vim.cmd("let g:airline_left_sep = ''")
vim.cmd("let g:airline_left_alt_sep = ''")
vim.cmd("let g:airline_right_sep = ''")
vim.cmd("let g:airline_right_alt_sep = ''")
vim.cmd("let g:airline_symbols.branch = ''")
vim.cmd("let g:airline_symbols.readonly = ''")
vim.cmd("let g:airline_symbols.linenr = ''")
